"""
models/alert.py - Alert Model
==============================
Stores every threat alert generated by the Detection Engine.

Fields:
  alert_id      - Primary key
  threat_type   - "port_scan" | "brute_force" | "ddos" | "suspicious_ip" | "traffic_spike"
  source_ip     - The attacking / suspicious source IP
  severity      - "critical" | "high" | "medium" | "low"
  message       - Human-readable alert description
  time_detected - UTC datetime when the alert was raised
  acknowledged  - Whether an analyst has reviewed this alert
  acknowledged_by - Username of the analyst who acknowledged it
  acknowledged_at - When it was acknowledged
  resolved      - Whether the threat has been resolved
  false_positive - Marked as a false positive by an analyst
  created_at    - Auto timestamp (TimestampMixin)
  updated_at    - Auto timestamp (TimestampMixin)
"""

from datetime import datetime, timezone

from database.db import BaseModel, TimestampMixin, db


class Alert(TimestampMixin, BaseModel):
    """
    Threat alert raised by the Detection Engine.

    Severity levels (highest → lowest):
      critical → immediate action required
      high     → investigate urgently
      medium   → investigate when possible
      low      → informational / monitor
    """

    __tablename__ = "alerts"

    __table_args__ = (
        db.Index("ix_alert_source_ip", "source_ip"),
        db.Index("ix_alert_time_detected", "time_detected"),
        db.Index("ix_alert_severity", "severity"),
        db.Index("ix_alert_threat_type", "threat_type"),
        db.Index("ix_alert_acknowledged", "acknowledged"),
    )

    # ------------------------------------------------------------------
    # Severity & threat type constants
    # ------------------------------------------------------------------
    SEVERITY_CRITICAL = "critical"
    SEVERITY_HIGH = "high"
    SEVERITY_MEDIUM = "medium"
    SEVERITY_LOW = "low"

    SEVERITY_LEVELS = [SEVERITY_CRITICAL, SEVERITY_HIGH, SEVERITY_MEDIUM, SEVERITY_LOW]

    THREAT_PORT_SCAN = "port_scan"
    THREAT_BRUTE_FORCE = "brute_force"
    THREAT_DDOS = "ddos"
    THREAT_SUSPICIOUS = "suspicious_ip"
    THREAT_TRAFFIC_SPIKE = "traffic_spike"

    THREAT_TYPES = [
        THREAT_PORT_SCAN,
        THREAT_BRUTE_FORCE,
        THREAT_DDOS,
        THREAT_SUSPICIOUS,
        THREAT_TRAFFIC_SPIKE,
    ]

    # ------------------------------------------------------------------
    # Columns
    # ------------------------------------------------------------------
    alert_id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    threat_type = db.Column(
        db.String(30),
        nullable=False,
        comment="Category of detected threat",
    )
    source_ip = db.Column(
        db.String(45),
        nullable=False,
        comment="IP address of the suspected attacker",
    )
    severity = db.Column(
        db.String(10),
        nullable=False,
        default="medium",
        comment="Alert severity: critical | high | medium | low",
    )
    message = db.Column(
        db.Text,
        nullable=False,
        comment="Human-readable description of the detected threat",
    )
    time_detected = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        comment="UTC datetime when the alert was generated",
    )

    # Acknowledgement workflow
    acknowledged = db.Column(
        db.Boolean,
        nullable=False,
        default=False,
        comment="True if an analyst has reviewed this alert",
    )
    acknowledged_by = db.Column(
        db.String(64),
        nullable=True,
        comment="Username of the analyst who acknowledged the alert",
    )
    acknowledged_at = db.Column(
        db.DateTime(timezone=True),
        nullable=True,
        comment="UTC datetime when the alert was acknowledged",
    )

    # Resolution
    resolved = db.Column(
        db.Boolean,
        nullable=False,
        default=False,
        comment="True if the threat has been resolved / mitigated",
    )
    false_positive = db.Column(
        db.Boolean,
        nullable=False,
        default=False,
        comment="True if an analyst marked this as a false positive",
    )

    # Email notification tracking
    email_sent = db.Column(
        db.Boolean,
        nullable=False,
        default=False,
        comment="True if an email notification was sent for this alert",
    )

    # ------------------------------------------------------------------
    # Business logic helpers
    # ------------------------------------------------------------------
    def acknowledge(self, analyst_username: str) -> None:
        """
        Mark the alert as acknowledged by the given analyst.

        Args:
            analyst_username: The username performing the acknowledgement.
        """
        self.acknowledged = True
        self.acknowledged_by = analyst_username
        self.acknowledged_at = datetime.now(timezone.utc)
        self.save()

    def mark_resolved(self) -> None:
        """Mark the alert as resolved."""
        self.resolved = True
        self.save()

    def mark_false_positive(self) -> None:
        """Mark the alert as a false positive."""
        self.false_positive = True
        self.acknowledged = True
        self.acknowledged_at = datetime.now(timezone.utc)
        self.save()

    @property
    def severity_badge_class(self) -> str:
        """
        Return a Bootstrap badge CSS class matching the alert severity.
        Used in Jinja2 templates: {{ alert.severity_badge_class }}
        """
        return {
            "critical": "badge bg-danger",
            "high": "badge bg-warning text-dark",
            "medium": "badge bg-info text-dark",
            "low": "badge bg-secondary",
        }.get(self.severity, "badge bg-secondary")

    # ------------------------------------------------------------------
    # Query helpers
    # ------------------------------------------------------------------
    @classmethod
    def get_unacknowledged(cls, limit: int = 50) -> list:
        """Return unacknowledged, non-false-positive alerts, newest first."""
        return (
            cls.query.filter_by(acknowledged=False, false_positive=False)
            .order_by(cls.time_detected.desc())
            .limit(limit)
            .all()
        )

    @classmethod
    def get_critical(cls, limit: int = 20) -> list:
        """Return unresolved critical alerts."""
        return (
            cls.query.filter_by(severity=cls.SEVERITY_CRITICAL, resolved=False)
            .order_by(cls.time_detected.desc())
            .limit(limit)
            .all()
        )

    @classmethod
    def count_by_severity(cls) -> dict:
        """
        Return a dict of severity → count for the dashboard widgets.

        Returns:
            dict: e.g. {"critical": 3, "high": 12, "medium": 5, "low": 20}
        """
        from sqlalchemy import func

        rows = (
            db.session.query(cls.severity, func.count(cls.alert_id).label("cnt"))
            .group_by(cls.severity)
            .all()
        )
        return {row.severity: row.cnt for row in rows}

    @classmethod
    def count_by_threat_type(cls) -> dict:
        """Return a dict of threat_type → count."""
        from sqlalchemy import func

        rows = (
            db.session.query(cls.threat_type, func.count(cls.alert_id).label("cnt"))
            .group_by(cls.threat_type)
            .all()
        )
        return {row.threat_type: row.cnt for row in rows}

    def to_dict(self) -> dict:
        """Serialise alert to a plain dict safe for JSON responses."""
        return {
            "alert_id":       self.alert_id,
            "threat_type":    self.threat_type,
            "source_ip":      self.source_ip,
            "severity":       self.severity,
            "message":        self.message,
            "time_detected":  self.time_detected.isoformat() if self.time_detected else None,
            "acknowledged":   self.acknowledged,
            "acknowledged_by": self.acknowledged_by,
            "acknowledged_at": self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            "resolved":       self.resolved,
            "false_positive": self.false_positive,
            "email_sent":     self.email_sent,
            "created_at":     self.created_at.isoformat() if self.created_at else None,
        }
